# 一、数组拼接

## Torch

### 1. torch.cat

In [3]:
import torch
a = torch.ones(10)
b = torch.zeros(10)
a,b

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [5]:
c = torch.cat((a,b),0)
d = torch.cat((a,b),-1)
c,d

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]))

In [7]:
m = torch.rand(2,3)
n = torch.rand(2,3)
m,n

(tensor([[0.4305, 0.5858, 0.6041],
         [0.3689, 0.7339, 0.3004]]),
 tensor([[0.3952, 0.5579, 0.6647],
         [0.3820, 0.1805, 0.4863]]))

In [15]:
s1 = torch.cat((m,n),0) #dim = 0 按列拼接
s1

tensor([[0.4305, 0.5858, 0.6041],
        [0.3689, 0.7339, 0.3004],
        [0.3952, 0.5579, 0.6647],
        [0.3820, 0.1805, 0.4863]])

In [16]:
s2 = torch.cat((m,n),dim=1) # dim=1, 按行拼接
s2

tensor([[0.4305, 0.5858, 0.6041, 0.3952, 0.5579, 0.6647],
        [0.3689, 0.7339, 0.3004, 0.3820, 0.1805, 0.4863]])

In [17]:
s3 = torch.cat((s2,m),dim=1)
s3

tensor([[0.4305, 0.5858, 0.6041, 0.3952, 0.5579, 0.6647, 0.4305, 0.5858, 0.6041],
        [0.3689, 0.7339, 0.3004, 0.3820, 0.1805, 0.4863, 0.3689, 0.7339, 0.3004]])

> **示例分析：** 
a是[10]的列表，a一直在变化，想把这些变化都拼接到一个数组中

In [20]:
a_all = []
for i in range(5):
    a = torch.rand(3)
    if i==0: a_all = a
    else: a_all = torch.cat((a_all,a),dim=0)
a_all

tensor([0.2426, 0.6465, 0.6805, 0.3972, 0.0939, 0.9206, 0.3735, 0.6619, 0.4411,
        0.6900, 0.4391, 0.4374, 0.4946, 0.9330, 0.0059])

In [22]:
a.shape

torch.Size([3])

In [23]:
a.reshape(-1,1)
a.shape

torch.Size([3])

**注意：**不能和空列表拼接

In [11]:
p = []
q = torch.rand(2,3)
p,q

([],
 tensor([[0.7906, 0.3794, 0.5541],
         [0.7933, 0.8305, 0.9623]]))

In [24]:
torch.cat((p,q),dim=0)

TypeError: expected Tensor as element 0 in argument 0, but got list

### 2. Torch.stack 用于在某个维度上相同的数组的拼接

In [27]:
s1 = torch.rand(2,3)
s1

tensor([[0.6762, 0.5598, 0.9276],
        [0.8154, 0.1286, 0.4169]])

In [28]:
s2 = torch.rand(2,3)
s2

tensor([[0.8296, 0.8844, 0.4930],
        [0.6506, 0.5582, 0.9268]])

In [29]:
torch.stack((s1,s2),dim=0)

tensor([[[0.6762, 0.5598, 0.9276],
         [0.8154, 0.1286, 0.4169]],

        [[0.8296, 0.8844, 0.4930],
         [0.6506, 0.5582, 0.9268]]])

In [30]:
torch.stack((s1,s2),dim=1)

tensor([[[0.6762, 0.5598, 0.9276],
         [0.8296, 0.8844, 0.4930]],

        [[0.8154, 0.1286, 0.4169],
         [0.6506, 0.5582, 0.9268]]])

In [32]:
w1 = torch.ones(10)
w2 = torch.zeros(10)
w1,w2

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [33]:
torch.stack((w1,w2),dim=0)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
torch.stack((w1,w2),dim=1)

tensor([[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]])

In [38]:
t1 = torch.stack((w1,w2),dim=1)
t1

tensor([[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]])

In [39]:
for t in t1:
    a,b = t.tolist()
    print(a,b)

1.0 0.0
1.0 0.0
1.0 0.0
1.0 0.0
1.0 0.0
1.0 0.0
1.0 0.0
1.0 0.0
1.0 0.0
1.0 0.0


# 二、数组操作

## 1. torch.sum

In [48]:
ss = torch.randn(10,5)
ss

tensor([[-0.3580, -0.3733,  0.9526, -0.2283,  1.9288],
        [ 1.3071, -1.1372, -0.5722, -1.2409, -0.0080],
        [ 0.5829, -1.0200, -0.1185, -1.2181,  0.0603],
        [-0.6280,  0.9144, -0.0768,  0.0363, -0.4285],
        [-0.7456,  0.4093, -1.8571,  0.1461,  1.0394],
        [ 1.6432, -1.3011, -0.8470, -0.7020,  0.1546],
        [ 0.9789, -0.3996, -0.1452,  0.3209,  0.6135],
        [ 0.2313,  0.7755,  0.8359, -1.2404,  0.1416],
        [ 0.1149,  0.5541, -0.5762,  0.4889, -0.5913],
        [-0.4622,  0.3965,  1.5930, -0.3442,  1.0517]])

In [50]:
torch.sum(ss,dim=0) #按列求和

tensor([ 2.6644, -1.1814, -0.8113, -3.9817,  3.9621])

In [51]:
torch.sum(ss,dim=1) #按行求和

tensor([ 1.9218, -1.6512, -1.7134, -0.1827, -1.0079, -1.0523,  1.3685,  0.7440,
        -0.0095,  2.2348])

## 2. 举例说明，寻找两个数组（具有相同的列）分别满足条件的个数

In [41]:
h1 = torch.randn(20,5)
h2 = torch.rand(20,5)
h1,h2

(tensor([[ 1.0787e-01,  3.6212e-01, -6.7001e-01, -1.3113e-01, -5.6334e-01],
         [ 3.7117e-01, -2.7837e-01,  5.3334e-01, -1.2462e-01, -4.6961e-01],
         [ 1.0620e-01,  1.0143e+00, -1.1995e-01, -1.5577e+00,  2.1638e+00],
         [-1.4423e+00,  6.7262e-01,  5.6922e-01, -2.6069e+00, -3.1958e-02],
         [ 4.6898e-01, -3.3921e-01,  9.3832e-01,  1.8161e-01,  1.4255e-03],
         [-4.4099e-01, -1.1822e+00,  4.9722e-01, -1.9459e+00, -2.0278e+00],
         [-4.1827e-01, -1.6319e+00,  4.0082e-01, -8.6108e-01,  8.6031e-01],
         [ 5.1789e-03, -1.0438e+00,  1.4234e+00, -8.3692e-01, -8.9327e-01],
         [ 1.1142e+00,  2.2890e+00,  9.1615e-03,  4.9670e-01, -4.2941e-01],
         [-4.6739e-01, -1.0803e+00, -6.6007e-01,  1.0975e+00, -1.6250e+00],
         [ 8.8541e-01,  6.2591e-01,  1.4147e+00, -1.0127e+00,  1.9216e-01],
         [ 1.2020e+00, -1.8767e-01, -1.0581e-01,  4.7640e-02,  5.6826e-01],
         [-5.0824e-01,  7.2207e-01,  1.1469e-01, -3.0354e-01, -5.7193e-01],
         [-1

In [43]:
mask1 = h1[:,0] > 0
mask1

tensor([ True,  True,  True, False,  True, False, False,  True,  True, False,
         True,  True, False, False,  True,  True, False, False, False,  True])

In [44]:
mask2 = h2[:,0] > 0.5
mask2

tensor([False, False,  True,  True,  True, False, False,  True, False,  True,
         True, False,  True,  True, False, False,  True, False, False, False])

In [45]:
torch.sum(mask1)

tensor(11)

In [46]:
torch.sum(mask2)

tensor(9)

In [47]:
torch.sum(mask1 & mask2) #两个数组共同满足条件的索引值个数为4

tensor(4)

## 3. 对齐输出

- 左对齐 .ljust(10, "-")
- 右对齐 .rjust(10, "-")
- 居中对齐 .center(10, "-")

In [53]:
classes = ['airplane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
classes[0]

'airplane'

In [54]:
for i in range(10):
    print("%s".ljust(10,"*")%classes[i])

airplane********
car********
bird********
cat********
deer********
dog********
frog********
horse********
ship********
truck********


In [55]:
for i in range(10):
    print("%s".rjust(10,"*")%classes[i])

********airplane
********car
********bird
********cat
********deer
********dog
********frog
********horse
********ship
********truck


In [56]:
for i in range(10):
    print("%s".center(10,"*")%classes[i])

****airplane****
****car****
****bird****
****cat****
****deer****
****dog****
****frog****
****horse****
****ship****
****truck****


In [57]:
s1 = 'long long long .'
s2 = 'short.'
 
print ('%-30s%-20s' %(s1,s2)) #'%-30s' 含义是 左对齐，且占用30个字符位 
print ('%-30s%-20s' %(s2,s1))

long long long .              short.              
short.                        long long long .    


In [58]:
s1 = 'long long long .'
s2 = 'short.'
print ('{:>30}{:>20}' .format(s1,s2)) #{:30d}含义是 右对齐，且占用30个字符位 
print ('{:<30}{:<20}' .format(s1,s2)) #{:<30d}含义是 左对齐，且占用30个字符位 
print ('{:^30}{:^20}' .format(s1,s2)) #{:<30d}含义是 左对齐，且占用30个字符位 

              long long long .              short.
long long long .              short.              
       long long long .              short.       
