# 生成随机数

# Torch

In [1]:
import torch

In [3]:
torch.tensor(5)

tensor(5)

In [2]:
# 1. torch.rand 均匀分布
a = torch.rand(2,3)
a

tensor([[0.2828, 0.0032, 0.2511],
        [0.1414, 0.3980, 0.8461]])

In [4]:
# 2. 标准正太分布 torch.randn 有负值
b = torch.randn(2,3)
b

tensor([[ 0.0188,  2.1887,  1.1742],
        [-0.8135, -2.7614,  0.1584]])

In [13]:
# 3. 离散正太分布 torch.normal(means, std,)
mean = torch.tensor([1,2,3],dtype=torch.float) #mean std的数据类型要保证
std = torch.tensor([1,1,1], dtype=torch.float)
torch.normal(mean, std)

tensor([0.6371, 1.8696, 2.2580])

In [12]:
# 4. 线性间距向量 torch.linsapce(start, end, steps=100) --> Tensor
torch.linspace(0,1,10) #包括首尾，产生的数相同

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

## Numpy

### 1. 生成器

- 随机数是随机种子根据一定的计算方法计算出来的数值，如果随机种子不变，那么，产生的随机数就不会变
- 只要不设置随机种子，默认情况下随机种子来自系统的时钟
- 随机数产生的算法与系统有关，不同系统产生的随机数不一样

> numpy.random设置种子的方法

| 函数名称 | 函数功能 | 参数说明 |
| -------- | -------- | -------- |
| RandomState | 定义种子类 | RandomState是一个种子类，提供各种种子方法，最常用的是seed |
| seed([seed]) | 定义全局种子 | 参数为整数或矩阵 |

In [16]:
import numpy as np

In [18]:
np.random.seed(1234) #设置随机种子

### 2. 简单随机数

In [19]:
# 均匀分布随机数 np.random.rand()
np.random.rand(2,3)

array([[0.19151945, 0.62210877, 0.43772774],
       [0.78535858, 0.77997581, 0.27259261]])

In [20]:
# 标准正态分布随机数 np.random.randn()
np.random.randn(2,3)

array([[ 0.85958841, -0.6365235 ,  0.01569637],
       [-2.24268495,  1.15003572,  0.99194602]])

In [21]:
# 随机整数 np.random.randint(low, high, size, dtype)
np.random.randint(0,10,(2,3))

array([[6, 2, 0],
       [5, 2, 6]])

In [22]:
# [0,1) 之间产生随机数 .random_sample([size])
np.random.random_sample([2,3])

array([[0.88264119, 0.36488598, 0.61539618],
       [0.07538124, 0.36882401, 0.9331401 ]])

In [23]:
# .random 同上
np.random.random([2,3])

array([[0.65137814, 0.39720258, 0.78873014],
       [0.31683612, 0.56809865, 0.86912739]])

In [24]:
# .sample([size]) 同上
np.random.sample([2,3])

array([[0.43617342, 0.80214764, 0.14376682],
       [0.70426097, 0.70458131, 0.21879211]])

In [30]:
# .choice(a[, size, replace, p]) 从a中随机选择指定数据, a 必须是一维数组
a = np.random.rand(10)
b = np.random.choice(a,size=[2,3])
print(a)
print(b)

[0.94812322 0.58364465 0.53155327 0.16865734 0.15880774 0.93796532
 0.71826456 0.47654265 0.88365336 0.40420231]
[[0.53155327 0.53155327 0.16865734]
 [0.53155327 0.40420231 0.47654265]]


### 3. 分布 numpy.random模块提供了产生多种分布随机数的API

| 函数名称 | 函数功能 |
| -------- | -------- |
| .beta(a,b[,size]) | 贝塔分布样本，在[0,1]之间 |
| .binomial(n,p[,size]) | 二项分布|
| chisquare(df[, size]) | 卡方分布 |
| dirichlet(alpha[, size]) | 狄利克雷分布 |
| exponential([scale, size]) | 指数分布 |
| f(dfnum, dfden[, size]) | F分布 |
| gamma(shape[, scale, size]) | 伽马分布 |
| geometric(p[, size]) | 几何分布 |
| hypergeometric(ngood, nbad, nsample[, size]) |  nbad, nsample[, size])	超几何分布样本 |
| **uniform([low, high, size])** | 均匀分布 |

### 排列


In [35]:
# .shuffle(x) 打乱顺序，多维矩阵按照第一维打乱
x = np.random.rand(2,3)
print(x)
np.random.shuffle(x) #直接打乱本身函数，不用赋值
print(x)

[[0.82893194 0.74284587 0.45703374]
 [0.07910336 0.37304659 0.93363636]]
[[0.07910336 0.37304659 0.93363636]
 [0.82893194 0.74284587 0.45703374]]


In [42]:
# .permutation(x) 打乱或并返回该对象，多维矩阵按第一维打乱
y = np.random.rand(3,6)
print(y)
s = np.random.permutation(y) #本身不变化，打乱后的矩阵赋值给新变量，二维矩阵按列打乱
print(y)
print(s)

[[0.32309469 0.87142326 0.21563406 0.73494519 0.36561909 0.8016026 ]
 [0.78273559 0.70135538 0.62277659 0.49368265 0.8405377  0.71209699]
 [0.44390898 0.03103486 0.36323976 0.73072179 0.47556657 0.34441697]]
[[0.32309469 0.87142326 0.21563406 0.73494519 0.36561909 0.8016026 ]
 [0.78273559 0.70135538 0.62277659 0.49368265 0.8405377  0.71209699]
 [0.44390898 0.03103486 0.36323976 0.73072179 0.47556657 0.34441697]]
[[0.44390898 0.03103486 0.36323976 0.73072179 0.47556657 0.34441697]
 [0.32309469 0.87142326 0.21563406 0.73494519 0.36561909 0.8016026 ]
 [0.78273559 0.70135538 0.62277659 0.49368265 0.8405377  0.71209699]]


In [43]:
s == y

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])